[package]
name = "owe"
version = "0.1.0"
authors = ["sndnv"]

[dependencies]
ndarray = "0.10.0"
uuid = { version = "0.5", features = ["v4"] }
pathfinding = "0.2"
actix = "0.4"
futures = "0.1"

[lib]
name = "owe"
path = "src/lib.rs"

[[bin]]
name = "owebin"
path = "src/main.rs"
